### ISSUE TITLE
Setting scope does not work

### ISSUE THREAD

**Issue by coffeine-009** [SocialiteProviders/Instagram#6]
Setting scopes before redirect to instgram does not ask instgram for get access token with this scope.
Socialite::driver($socialName)->-> scopes(['relationships'])-> redirect();

**Comment by CreativityKills** [comment]
The OAuth 2.0 specification allows you to specify the scope of the access you are requesting from the user. All apps have basic read access by default, but if you plan on asking for extended access such as liking, commenting, or managing friendships, you need to specify these scopes in your authorization request. **Note that in order to use these extended permissions, first you need to submit your app for review. For more information on how to submit your app for review**, please check out the documentation of the endpoint that you plan to use. Here are the scopes we currently support:
